In [11]:

import numpy as np

#Q1

#a
v=np.array([2,3.8,0,5,1])
print("Q1. a")
print(v,"\n")

#b
u=np.arange(1,11,2).reshape(5,1)
u=np.exp(u)
print("Q1. b")
print(u,"\n")

#c
w=np.arange(-10,4)
print("Q1. c")
print(w,"\n")

#d
m=np.arange(-3,9,2)
print("Q1. d")
print(m,"\n")


#e
n=np.arange(0,8,2)
print("Q1. e")
print(n,"\n")


#f
s=np.arange(0,-3.1,-0.1).reshape(31,1)
print("Q1. f")
print(s,"\n")


#g
t=np.linspace(0,np.pi,50).reshape(50,1)
print("Q1. g")
print(t,"\n")



Q1. a
[2.  3.8 0.  5.  1. ] 

Q1. b
[[2.71828183e+00]
 [2.00855369e+01]
 [1.48413159e+02]
 [1.09663316e+03]
 [8.10308393e+03]] 

Q1. c
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3] 

Q1. d
[-3 -1  1  3  5  7] 

Q1. e
[0 2 4 6] 

Q1. f
[[ 0. ]
 [-0.1]
 [-0.2]
 [-0.3]
 [-0.4]
 [-0.5]
 [-0.6]
 [-0.7]
 [-0.8]
 [-0.9]
 [-1. ]
 [-1.1]
 [-1.2]
 [-1.3]
 [-1.4]
 [-1.5]
 [-1.6]
 [-1.7]
 [-1.8]
 [-1.9]
 [-2. ]
 [-2.1]
 [-2.2]
 [-2.3]
 [-2.4]
 [-2.5]
 [-2.6]
 [-2.7]
 [-2.8]
 [-2.9]
 [-3. ]] 

Q1. g
[[0.        ]
 [0.06411414]
 [0.12822827]
 [0.19234241]
 [0.25645654]
 [0.32057068]
 [0.38468481]
 [0.44879895]
 [0.51291309]
 [0.57702722]
 [0.64114136]
 [0.70525549]
 [0.76936963]
 [0.83348377]
 [0.8975979 ]
 [0.96171204]
 [1.02582617]
 [1.08994031]
 [1.15405444]
 [1.21816858]
 [1.28228272]
 [1.34639685]
 [1.41051099]
 [1.47462512]
 [1.53873926]
 [1.60285339]
 [1.66696753]
 [1.73108167]
 [1.7951958 ]
 [1.85930994]
 [1.92342407]
 [1.98753821]
 [2.05165235]
 [2.11576648]
 [2.17988062]
 [2.24

In [12]:
#Q2

#a
A=np.array([[1,2,3],[5,3,1],[7,7,7]])
print("Q2. a")
print(A,"\n")

#b
tmp=np.zeros((5,5))
print("Q2. b")
print(tmp,"\n")

#c
B=2*np.ones((5,5))
print("Q2. c")
print(B,"\n")

#d
C=5*np.ones((5,5))-5*np.identity(5)
print("Q2. d")
print(C,"\n")

#e
D=np.diag([1,2,3,2,1])
print("Q2. e")
print(D,"\n")

#f
F=np.ones((9,5))*np.arange(1,10).reshape(9,1)
print("Q2. f")
print(F,"\n")



Q2. a
[[1 2 3]
 [5 3 1]
 [7 7 7]] 

Q2. b
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

Q2. c
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]] 

Q2. d
[[0. 5. 5. 5. 5.]
 [5. 0. 5. 5. 5.]
 [5. 5. 0. 5. 5.]
 [5. 5. 5. 0. 5.]
 [5. 5. 5. 5. 0.]] 

Q2. e
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 2 0]
 [0 0 0 0 1]] 

Q2. f
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9.]] 



In [13]:
#Q3

#a
a=0.5*np.log10(v)
print("Q3. a")
print(a,"\n")

#b
b=np.exp(u)
print("Q3. b")
print(b,"\n")

#c
c=np.abs(w)-3
print("Q3. c")
print(c,"\n")

#d
d=np.cos(t)
print("Q3. d")
print(d,"\n")

#e
A=np.fliplr(A)
print("Q3. e")
print(A,"\n")


#f
B[0]=np.ones((1,5))
B[2]=np.ones((1,5))*3
print("Q3. f")
print(B,"\n")


#g
D=np.delete(D,1,0)
print("Q3. g")
print(D,"\n")


#h
C2=C[np.ix_([0,1],[3,4])]
print("Q3. h")
print(C2,"\n")


#i
F[:,0]=np.flipud(F[:,0])
print("Q3. j")
print(F,"\n")


Q3. a
[0.150515  0.2898918      -inf 0.349485  0.       ] 

Q3. b
[[1.51542622e+01]
 [5.28491311e+08]
 [2.85112357e+64]
 [           inf]
 [           inf]] 

Q3. c
[ 7  6  5  4  3  2  1  0 -1 -2 -3 -2 -1  0] 

Q3. d
[[ 1.        ]
 [ 0.99794539]
 [ 0.99179001]
 [ 0.98155916]
 [ 0.96729486]
 [ 0.94905575]
 [ 0.92691676]
 [ 0.90096887]
 [ 0.8713187 ]
 [ 0.8380881 ]
 [ 0.80141362]
 [ 0.76144596]
 [ 0.71834935]
 [ 0.67230089]
 [ 0.6234898 ]
 [ 0.57211666]
 [ 0.51839257]
 [ 0.46253829]
 [ 0.40478334]
 [ 0.34536505]
 [ 0.28452759]
 [ 0.22252093]
 [ 0.1595999 ]
 [ 0.09602303]
 [ 0.03205158]
 [-0.03205158]
 [-0.09602303]
 [-0.1595999 ]
 [-0.22252093]
 [-0.28452759]
 [-0.34536505]
 [-0.40478334]
 [-0.46253829]
 [-0.51839257]
 [-0.57211666]
 [-0.6234898 ]
 [-0.67230089]
 [-0.71834935]
 [-0.76144596]
 [-0.80141362]
 [-0.8380881 ]
 [-0.8713187 ]
 [-0.90096887]
 [-0.92691676]
 [-0.94905575]
 [-0.96729486]
 [-0.98155916]
 [-0.99179001]
 [-0.99794539]
 [-1.        ]] 

Q3. e
[[3 2 1]
 [1 3 5]
 [7 7 

<ipython-input-13-482e521323d5>:4: RuntimeWarning: divide by zero encountered in log10
  a=0.5*np.log10(v)
<ipython-input-13-482e521323d5>:9: RuntimeWarning: overflow encountered in exp
  b=np.exp(u)
